--- Reusable icons for consistent symbols
return {
    diagnostics = {
        Error = " ",
        Warn = " ",
        Hint = "󰌵",
        Info = " ",
    },
    git = {
        added = " ",
        modified = " ",
        removed = " ",
    },
    kinds = {
        Array = " ",
        Boolean = " ",
        Class = " ",
        Color = " ",
        Copilot = " ",
        Constant = " ",
        Constructor = "󰡢 ",
        Enum = " ",
        EnumMember = " ",
        Event = " ",
        Field = " ",
        File = " ",
        Folder = " ",
        Function = "󰊕",
        Interface = " ",
        Key = " ",
        Keyword = " ",
        Method = " ",
        Module = " ",
        Namespace = " ",
        Null = "ﳠ ",
        Number = " ",
        Object = " ",
        Operator = " ",
        Package = " ",
        Property = " ",
        Reference = " ",
        Snippet = " ",
        String = " ",
        Struct = " ",
        Text = "󰉿 ",
        TypeParameter = " ",
        Unit = " ",
        Value = " ",
        Variable = " ",
    },
    file_status = {
        modified = "",
        readonly = "",
        unnamed = "[No Name]",
        newfile = "",
    },
    ui = {
        gutter = "▍",
        powerline = {
            separators = { left = "", right = "" },
            inner_separators = { left = "", right = "" },
        },
    },
}
