--- Filetypes helpers

return {
    --- Buffer filetypes to exclude from plugin
    internals = {
        "Avante",
        "AvanteInput",
        "NeogitStatus",
        "NvimTree",
        "Outline",
        "Trouble",
        "cmp_menu",
        "codecompanion",
        "copilot-chat",
        "flash_prompt",
        "grug-far",
        "help",
        "lazy",
        "mason",
        "neo-tree",
        "neotest-output-panel",
        "neotest-summary",
        "noice",
        "notify",
        "qf",
        "snacks_dashboard",
        "snacks_notif",
        "snacks_notif_history",
        "snacks_terminal",
        "snacks_win",
        "telescope",
        "toggleterm",
        "trouble",
    },
}
